#' Aggregate daily values of SWAT.profile to Monthly values
#'
#' @param dat data.frame or data.table of SWAT.profile aggregate daily profile water
#' contents, generated by \code{\link{AggregateSWATi}}
#'
#' @return a data.table with monthly aggregated values and stress-indicators
#' integrating over vegetation or other intervals
#' @export
states_soil_daymon <- function(dat) {
  data.table::setDT(dat)
  dat_month <- dat[,list(
    #SWAT
    vrfl_we = sum(vrfl_we),
    SWAT_prf_avg = round(mean(SWAT_prf),1),
    SWAT_prf_min = round(min(SWAT_prf),1),
    SWAT_prf_end = SWAT_prf[which.max(da)],

    SWAT_we_avg = round(mean(SWAT_we),1),
    SWAT_we_min = round(min(SWAT_we),1),
    SWAT_we_end = SWAT_we[which.max(da)],
#     SWAT_090_avg = round(mean(SWAT_090),1),
#     SWAT_090_min = round(min(SWAT_090),1),
#     SWAT_090_end = SWAT_090[which.max(da)],
    SWAT_030_avg = round(mean(SWAT_030),1),
    SWAT_030_min = round(min(SWAT_030),1),
    SWAT_030_end = SWAT_030[which.max(da)],
    #AWAT
    AWAT_we_avg = round(mean(AWAT_we),1),
    AWAT_we_min = round(min(AWAT_we),1),
#     AWAT_090_avg = round(mean(AWAT_090),1),
#     AWAT_090_min = round(min(AWAT_090),1),
    AWAT_030_avg = round(mean(AWAT_030),1),
    AWAT_030_min = round(min(AWAT_030),1),

    RELSWAT_we_avg = round(mean(RELSWAT_we),4),
    RELSWAT_we_min = round(min(RELSWAT_we),4),
    #     RELAWAT_090_avg = round(mean(RELAWAT_090),4),
    #     RELAWAT_090_min = round(min(RELAWAT_090),4),
    RELSWAT_030_avg = round(mean(RELSWAT_030),4),
    RELSWAT_030_min = round(min(RELSWAT_030),4),

    #RELAWAT
    RELAWAT_we_avg = round(mean(RELAWAT_we),4),
    RELAWAT_we_min = round(min(RELAWAT_we),4),
#     RELAWAT_090_avg = round(mean(RELAWAT_090),4),
#     RELAWAT_090_min = round(min(RELAWAT_090),4),
    RELAWAT_030_avg = round(mean(RELAWAT_030),4),
    RELAWAT_030_min = round(min(RELAWAT_030),4),

    #MISC
#    ADEF_avg = round(mean(adef),3),
#    ADEF_max = round(max(adef),3),
#    AWAT40_avg = round(mean(awat40),1),
#    AWAT40_min = round(min(awat40),1),

    #PSI
    PSIlogmean_we_avg = round(mean(PSIlogmean_we),1),
    PSIlogmean_we_min = round(min(PSIlogmean_we),1),
#     PSIlogmean_090_avg = round(mean(PSIlogmean_090),1),
#     PSIlogmean_090_min = round(min(PSIlogmean_090),1),
    PSIlogmean_030_avg = round(mean(PSIlogmean_030),1),
    PSIlogmean_030_min = round(min(PSIlogmean_030),1),
    #StagWat
    WaterTableDepth_min = round(min(WaterTableDepth),3),
    WaterTableDepth_max = round(max(WaterTableDepth, na.rm=T),3),
    WaterTableDepth_avg = round(mean(WaterTableDepth),3),

    Days_SaturatedCond30cm = sum(WaterTableDepth>=-0.3),
    Days_SaturatedCond60cm = sum(WaterTableDepth>=-0.6),
    Durations_Saturated30cm = paste((rle(WaterTableDepth >= -0.3)$lengths[rle(WaterTableDepth >= -0.3)$values]), collapse = " "),
    Durations_Saturated60cm = paste((rle(WaterTableDepth >= -0.6)$lengths[rle(WaterTableDepth >= -0.6)$values]), collapse = " "),

    #PSI-Stress
    Days_PsiWe_lower1200 = sum(PSIlogmean_we < -1200),
    Durations_Psiwe_lower1200 = paste((rle(PSIlogmean_we < -1200)$lengths[rle(PSIlogmean_we < -1200)$values]), collapse = " "),
    Defsum_PsiWe_lower1200 = round(sum( (PSIlogmean_we+1200) * (PSIlogmean_we < -1200)),2),

#     Days_Psi090_lower1200 = sum(PSIlogmean_090 < -1200),
#     Durations_Psi090_lower1200 = paste((rle(PSIlogmean_090 < -1200)$lengths[rle(PSIlogmean_090 < -1200)$values]), collapse = " "),
#     Defsum_Psi090_lower1200 = round(sum( (PSIlogmean_090+1200) * (PSIlogmean_090 < -1200)),2),
#
    Days_Psi030_lower1200 = sum(PSIlogmean_030 < -1200),
    Durations_Psi030_lower1200 = paste((rle(PSIlogmean_030 < -1200)$lengths[rle(PSIlogmean_030 < -1200)$values]), collapse = " "),
    Defsum_Psi030_lower1200 = round(sum( (PSIlogmean_030+1200) * (PSIlogmean_030 < -1200)),2),

    #REW-STRESS 40% nFK
    Days_RELAWATwe_lower40 = sum(RELAWAT_we < 0.4),
    Durations_RELAWATwe_lower40 = paste((rle(RELAWAT_we < 0.4)
                                         $lengths[rle(RELAWAT_we < 0.4)$values]), collapse = " "),
    Defsum_RELAWATwe_lower40 = round(sum((1 - (RELAWAT_we/0.4))*(RELAWAT_we < 0.4)),2),

#     Days_RELAWAT090_lower40 = sum(RELAWAT_090 < 0.4),
#     Durations_RELAWAT090_lower40 = paste((rle(RELAWAT_090 < 0.4)
#                                           $lengths[rle(RELAWAT_090 < 0.4)$values]), collapse = " "),
#     Defsum_RELAWAT090_lower40 = round(sum((1 - (RELAWAT_090/0.4))*(RELAWAT_090 < 0.4)),2),
#
    Days_RELAWAT030_lower40 = sum(RELAWAT_030 < 0.4),
    Durations_RELAWAT030_lower40 = paste((rle(RELAWAT_030 < 0.4)
                                          $lengths[rle(RELAWAT_030 < 0.4)$values]), collapse = " "),
    Defsum_RELAWAT030_lower40 = round(sum((1 - (RELAWAT_030/0.4))*(RELAWAT_030 < 0.4)),2),

    #REW-STRESS 20% nFK
    Days_RELAWATwe_lower20 = sum(RELAWAT_we < 0.2),
    Durations_RELAWATwe_lower20 = paste((rle(RELAWAT_we < 0.2)
                                         $lengths[rle(RELAWAT_we < 0.2)$values]), collapse = " "),
    Defsum_RELAWATwe_lower20 = round(sum((1 - (RELAWAT_we/0.2))*(RELAWAT_we < 0.2)),2),

#     Days_RELAWAT090_lower20 = sum(RELAWAT_090 < 0.2),
#     Durations_RELAWAT090_lower20 = paste((rle(RELAWAT_090 < 0.2)
#                                           $lengths[rle(RELAWAT_090 < 0.2)$values]), collapse = " "),
#     Defsum_RELAWAT090_lower20 = round(sum((1 - (RELAWAT_090/0.2))*(RELAWAT_090 < 0.2)),2),

    Days_RELAWAT030_lower20 = sum(RELAWAT_030 < 0.2),
    Durations_RELAWAT030_lower20 = paste((rle(RELAWAT_030 < 0.2)
                                          $lengths[rle(RELAWAT_030 < 0.2)$values]), collapse = " "),
    Defsum_RELAWAT030_lower20 = round(sum((1 - (RELAWAT_030/0.2))*(RELAWAT_030 < 0.2)),2)


  ),
  by=list(yr, mo)]
  return(dat_month)
}
